---
# tasks file for david_igou.routeros_configuration.interface_wireguard
- name: "Reconcile interface wireguard"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface wireguard
    rcfg_data: "{{ routeros_interface_wireguard }}"
    rcfg_purge: "{{ routeros_interface_wireguard_purge | default(false) }}"
    rcfg_order: false
