---
# tasks file for david_igou.routeros_configuration.ip_ssh
- name: "Reconcile ip ssh"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip ssh
    rcfg_data: "{{ routeros_ip_ssh }}"
    rcfg_purge: false
    rcfg_order: false
