---
- name: Converge — add a (disabled) dhcp-relay on ether5
  hosts: molecule
  gather_facts: false
  vars:
    routeros_ip_dhcp_relay:
      - name: relay-test
        interface: ether5
        dhcp-server: "192.168.60.1"
        disabled: true
  roles:
    - role: david_igou.routeros_configuration.ip_dhcp_relay
