---
# tasks file for david_igou.routeros_configuration.ip_firewall_mangle
- name: Reconcile ip firewall mangle
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip firewall mangle
    rcfg_data: "{{ routeros_ip_firewall_mangle }}"
    rcfg_purge: "{{ routeros_ip_firewall_mangle_purge }}"
    rcfg_order: "{{ routeros_ip_firewall_mangle_order }}"
    rcfg_content: "{{ routeros_ip_firewall_mangle_content }}"
