---
# tasks file for david_igou.routeros_configuration.interface_ethernet
- name: "Reconcile interface ethernet"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface ethernet
    rcfg_data: "{{ routeros_interface_ethernet }}"
    rcfg_purge: "{{ routeros_interface_ethernet_purge | default(false) }}"
    rcfg_order: false
