---
# tasks file for david_igou.routeros_configuration.ip_dhcp_server
- name: "Reconcile ip dhcp-server"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip dhcp-server
    rcfg_data: "{{ routeros_ip_dhcp_server }}"
    rcfg_purge: "{{ routeros_ip_dhcp_server_purge | default(false) }}"
    rcfg_order: false
