---
# tasks file for david_igou.routeros_configuration.interface_wireguard_peers
- name: "Reconcile interface wireguard peers"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface wireguard peers
    rcfg_data: "{{ routeros_interface_wireguard_peers }}"
    rcfg_purge: "{{ routeros_interface_wireguard_peers_purge | default(false) }}"
    rcfg_order: false
