---
# tasks file for david_igou.routeros_configuration.ip_dhcp_server_option
- name: "Reconcile ip dhcp-server option"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip dhcp-server option
    rcfg_data: "{{ routeros_ip_dhcp_server_option }}"
    rcfg_purge: "{{ routeros_ip_dhcp_server_option_purge | default(false) }}"
    rcfg_order: false
