---
# tasks file for david_igou.routeros_configuration.system_identity
- name: Reconcile /system/identity
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: system identity
    rcfg_data: "{{ routeros_system_identity }}"
    rcfg_purge: false
    rcfg_order: false
