---
- name: Converge — add a (disabled) dhcp-client on ether5
  hosts: molecule
  gather_facts: false
  vars:
    routeros_ip_dhcp_client:
      - interface: ether5
        disabled: true
        add-default-route: false
  roles:
    - role: david_igou.routeros_configuration.ip_dhcp_client
