---
# tasks file for david_igou.routeros_configuration.ip_settings
- name: "Reconcile ip settings"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip settings
    rcfg_data: "{{ routeros_ip_settings }}"
    rcfg_purge: false
    rcfg_order: false
