---
# tasks file for david_igou.routeros_configuration.ip_firewall_nat
- name: Reconcile ip firewall nat
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip firewall nat
    rcfg_data: "{{ routeros_ip_firewall_nat }}"
    rcfg_purge: "{{ routeros_ip_firewall_nat_purge }}"
    rcfg_order: "{{ routeros_ip_firewall_nat_order }}"
    rcfg_content: "{{ routeros_ip_firewall_nat_content }}"
