---
# tasks file for david_igou.routeros_configuration.interface_list_member
- name: "Reconcile interface list member"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface list member
    rcfg_data: "{{ routeros_interface_list_member }}"
    rcfg_purge: "{{ routeros_interface_list_member_purge | default(false) }}"
    rcfg_order: false
