---
# tasks file for david_igou.routeros_configuration.interface_vrrp
- name: "Reconcile interface vrrp"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface vrrp
    rcfg_data: "{{ routeros_interface_vrrp }}"
    rcfg_purge: "{{ routeros_interface_vrrp_purge | default(false) }}"
    rcfg_order: false
