---
# tasks file for david_igou.routeros_configuration.ip_dhcp_relay
- name: "Reconcile ip dhcp-relay"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip dhcp-relay
    rcfg_data: "{{ routeros_ip_dhcp_relay }}"
    rcfg_purge: "{{ routeros_ip_dhcp_relay_purge | default(false) }}"
    rcfg_order: false
