---
# tasks file for
# david_igou.routeros_configuration.ip_firewall_connection_tracking
- name: "Reconcile ip firewall connection tracking"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip firewall connection tracking
    rcfg_data: "{{ routeros_ip_firewall_connection_tracking }}"
    rcfg_purge: false
    rcfg_order: false
