---
# tasks file for david_igou.routeros_configuration.ip_firewall_raw
- name: Reconcile ip firewall raw
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip firewall raw
    rcfg_data: "{{ routeros_ip_firewall_raw }}"
    rcfg_purge: "{{ routeros_ip_firewall_raw_purge }}"
    rcfg_order: "{{ routeros_ip_firewall_raw_order }}"
    rcfg_content: "{{ routeros_ip_firewall_raw_content }}"
