---
# tasks file for david_igou.routeros_configuration.ip_dns
- name: "Reconcile ip dns"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip dns
    rcfg_data: "{{ routeros_ip_dns }}"
    rcfg_purge: false
    rcfg_order: false
