---
- name: Converge — add a dhcp-server option
  hosts: molecule
  gather_facts: false
  vars:
    routeros_ip_dhcp_server_option:
      - name: opt-tftp
        code: 66
        value: "'192.168.60.1'"
  roles:
    - role: david_igou.routeros_configuration.ip_dhcp_server_option
