---
# tasks file for david_igou.routeros_configuration.ip_firewall_filter
- name: Reconcile /ip/firewall/filter
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip firewall filter
    rcfg_data: "{{ routeros_ip_firewall_filter }}"
    rcfg_purge: "{{ routeros_ip_firewall_filter_purge }}"
    rcfg_order: "{{ routeros_ip_firewall_filter_order }}"
    rcfg_content: "{{ routeros_ip_firewall_filter_content }}"
