---
- name: Converge — wg-test interface
  hosts: molecule
  gather_facts: false
  vars:
    routeros_interface_wireguard:
      - name: wg-test
        listen-port: 13231
  roles:
    - role: david_igou.routeros_configuration.interface_wireguard
