---
# tasks file for david_igou.routeros_configuration.ip_service
- name: "Reconcile ip service"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip service
    rcfg_data: "{{ routeros_ip_service }}"
    rcfg_purge: false
    rcfg_order: false
