---
argument_specs:
  main:
    short_description: Manage /interface/bridge/port membership.
    options:
      routeros_interface_bridge_port:
        type: list
        elements: dict
        default: []
        description: Bridge port memberships.
      routeros_interface_bridge_port_purge:
        type: bool
        default: false
        description: Remove entries not present in the list.
