---
# tasks file for david_igou.routeros_configuration.interface_eoip
- name: "Reconcile interface eoip"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface eoip
    rcfg_data: "{{ routeros_interface_eoip }}"
    rcfg_purge: "{{ routeros_interface_eoip_purge | default(false) }}"
    rcfg_order: false
