---
- name: Converge — create WAN and LAN lists
  hosts: molecule
  gather_facts: false
  vars:
    routeros_interface_list:
      - {name: WAN}
      - {name: LAN}
  roles:
    - role: david_igou.routeros_configuration.interface_list
