---
# tasks file for david_igou.routeros_configuration.ip_dhcp_server_lease
- name: "Reconcile ip dhcp-server lease"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip dhcp-server lease
    rcfg_data: "{{ routeros_ip_dhcp_server_lease }}"
    rcfg_purge: "{{ routeros_ip_dhcp_server_lease_purge | default(false) }}"
    rcfg_order: false
