---
argument_specs:
  main:
    short_description: Manage /interface/list declaratively.
    options:
      routeros_interface_list:
        type: list
        elements: dict
        default: []
        description: Interface lists (logical groupings).
      routeros_interface_list_purge:
        type: bool
        default: false
        description: Remove entries not present in the list.
