---
- name: Converge — set neighbor discovery interface list to none
  hosts: molecule
  gather_facts: false
  vars:
    routeros_ip_neighbor_discovery_settings:
      - discover-interface-list: none
  roles:
    - role: david_igou.routeros_configuration.ip_neighbor_discovery_settings
