---
# tasks file for david_igou.routeros_configuration.interface_vlan
- name: "Reconcile interface vlan"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface vlan
    rcfg_data: "{{ routeros_interface_vlan }}"
    rcfg_purge: "{{ routeros_interface_vlan_purge | default(false) }}"
    rcfg_order: false
