---
argument_specs:
  main:
    short_description: Manage /interface/bonding declaratively.
    options:
      routeros_interface_bonding:
        type: list
        elements: dict
        default: []
        description: Bonding (link aggregation) interfaces.
      routeros_interface_bonding_purge:
        type: bool
        default: false
        description: Remove entries not present in the list.
