---
# tasks file for david_igou.routeros_configuration.ip_firewall_address_list
- name: "Reconcile ip firewall address-list"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: ip firewall address-list
    rcfg_data: "{{ routeros_ip_firewall_address_list }}"
    rcfg_purge: "{{ routeros_ip_firewall_address_list_purge | default(false) }}"
    rcfg_order: false
