---
# tasks file for david_igou.routeros_configuration.interface_vxlan
- name: "Reconcile interface vxlan"
  ansible.builtin.include_role:
    name: _reconcile
  vars:
    rcfg_path: interface vxlan
    rcfg_data: "{{ routeros_interface_vxlan }}"
    rcfg_purge: "{{ routeros_interface_vxlan_purge | default(false) }}"
    rcfg_order: false
