---
argument_specs:
  main:
    short_description: Manage /interface/wireguard/peers declaratively.
    options:
      routeros_interface_wireguard_peers:
        type: list
        elements: dict
        default: []
        description: WireGuard peers.
      routeros_interface_wireguard_peers_purge:
        type: bool
        default: false
        description: Remove entries not present in the list.
